export const SELECT_CATEGORY = "SELECT_CATEGORY";
export const ACTIVE_CATEGORY = "ACTIVE_CATEGORY";

export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const START_CONSULT_PRODUCT = 'START_CONSULT_PRODUCT';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const START_SEND_CONTACTINFO = 'START_SEND_CONTACTINFO';
export const SUCCESS_SEND_CONTACTINFO = 'SUCCESS_SEND_CONTACTINFO';
export const ERROR_SEND_CONTACTINFO = 'ERROR_SEND_CONTACTINFO';
